---
- name: try reduce swap
  sysctl:
    name: vm.swappiness
    value: "5"
    sysctl_set: yes
    state: present
    reload: yes

- name: Reduce reclaiming memory
  sysctl:
    name: vm.vfs_cache_pressure
    value: "50"
    sysctl_set: yes
    state: present
    reload: yes

# from 10
- name: dirty_background_ratio
  sysctl:
    name: vm.dirty_background_ratio
    value: "10"
    sysctl_set: yes
    state: present
    reload: yes

# 512 MB
- name: Try prevent small periodic system freezes dirty_ratio
  sysctl:
    name: vm.dirty_bytes
    value: "536870912"
    sysctl_set: yes
    state: present
    reload: yes

# 64 MB
- name: Try prevent small periodic system freezes dirty_background_bytes
  sysctl:
    name: vm.dirty_background_bytes
    value: "67108864"
    sysctl_set: yes
    state: present
    reload: yes

- name: Disable System Request
  sysctl:
    name: kernel.sysrq
    value: "0"
    sysctl_set: yes
    state: present
    reload: yes

- name: Increase allowed watchers
  sysctl:
    name: fs.inotify.max_user_watches
    value: "524288"
    sysctl_set: yes
    state: present
    reload: yes

- name: Reboot on kernel panic
  sysctl:
    name: kernel.panic
    value: "3"
    sysctl_set: yes
    state: present
    reload: yes

- name: Increase mmap counts
  sysctl:
    name: vm.max_map_count
    value: "262144"
    sysctl_set: yes
    state: present
    reload: yes

- name: Increase aio-max-nr
  sysctl:
    name: fs.aio-max-nr
    value: "1048576"
    sysctl_set: yes
    state: present
    reload: yes

- name: Increase system file descriptor limit
  sysctl:
    name: fs.file-max
    value: "6815744"
    sysctl_set: yes
    state: present
    reload: yes

- name: Allow for more PIDs
  sysctl:
    name: kernel.pid_max
    value: "65536"
    sysctl_set: yes
    state: present
    reload: yes

- name: speedup raid sync
  sysctl:
    name: dev.raid.speed_limit_min
    value: "50000"
    sysctl_set: yes
    state: present
    reload: yes

- name: speedup raid sync
  sysctl:
    name: dev.raid.speed_limit_max
    value: "5000000"
    sysctl_set: yes
    state: present
    reload: yes

#https://wiki.archlinux.org/index.php/sysctl
- name: enbale ipv6 all
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: "1"
    sysctl_set: yes
    state: absent
    reload: yes
- sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: "1"
    sysctl_set: yes
    state: absent
    reload: yes
- sysctl:
    name: net.ipv6.conf.lo.disable_ipv6
    value: "1"
    sysctl_set: yes
    state: absent
    reload: yes

- name: Enable syncookies
  sysctl:
    name: net.ipv4.tcp_syncookies
    value: "1"
    sysctl_set: yes
    state: absent
    reload: yes

- name: Accept packets with SRR option? No
  sysctl:
    name: net.ipv4.conf.default.accept_source_route
    value: "0"
    sysctl_set: yes
    state: absent
    reload: yes

- name: Enable source route verification
  sysctl:
    name: net.ipv4.conf.default.rp_filter
    value: "1"
    sysctl_set: yes
    state: absent
    reload: yes
- sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: "1"
    sysctl_set: yes
    state: absent
    reload: yes

- name: Log martian packets
  sysctl:
    name: net.ipv4.conf.default.log_martians
    value: "1"
    sysctl_set: yes
    state: absent
    reload: yes
- sysctl:
    name: net.ipv4.conf.all.log_martians
    value: "1"
    sysctl_set: yes
    state: absent
    reload: yes

- name: Send redirects, if router, but this is just server
  sysctl:
    name: net.ipv4.conf.all.send_redirects
    value: "0"
    sysctl_set: yes
    state: absent
    reload: yes
- sysctl:
    name: net.ipv4.conf.default.send_redirects
    value: "0"
    sysctl_set: yes
    state: absent
    reload: yes

- name: Ignore bogus errors
  sysctl:
    name: net.ipv4.icmp_ignore_bogus_error_responses
    value: "0"
    sysctl_set: yes
    state: absent
    reload: yes

- name: Improve tcp latency
  sysctl:
    name: net.ipv4.tcp_low_latency
    value: "1"
    sysctl_set: yes
    state: absent
    reload: yes

- name: Enable the TCP selective acks option for better throughput
  sysctl:
    name: net.ipv4.tcp_sack
    value: "1"
    sysctl_set: yes
    state: absent
    reload: yes

- name: Increase max connections
  sysctl:
    name: net.core.somaxconn
    value: "2048"
    sysctl_set: yes
    state: present
    reload: yes

- name: Increase max connections
  sysctl:
    name: net.ipv4.tcp_adv_win_scale
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: Increase allowed ports
  sysctl:
    name: net.ipv4.ip_local_port_range
    value: "2000 65535"
    sysctl_set: yes
    state: absent
    reload: yes

- name: Increase number of incoming connections backlog
  sysctl:
    name: net.core.netdev_max_backlog
    value: "250000"
    sysctl_set: yes
    state: absent
    reload: yes

- sysctl:
    name: net.core.netdev_budget_usecs
    value: "5000"
    sysctl_set: yes
    state: absent
    reload: yes

- name: Increase net budget
  sysctl:
    name: net.core.netdev_budget
    value: "100000"
    sysctl_set: yes
    state: absent
    reload: yes

- name: Set tcp_mem
  sysctl:
    name: net.ipv4.tcp_mem
    value: "8388608 8388608 8388608"
    sysctl_set: yes
    state: absent
    reload: yes

- name: Set tcp_rmem
  sysctl:
    name: net.ipv4.tcp_rmem
    value: "16384 349520 16777216"
    sysctl_set: yes
    state: present
    reload: yes

- name: Set tcp_wmem
  sysctl:
    name: net.ipv4.tcp_wmem
    value: "4096 65536 8388608"
    sysctl_set: yes
    state: absent
    reload: yes

- name: Increase Linux autotuning TCP buffer limits
  sysctl:
    name: net.core.rmem_max
    value: "16777216"
    sysctl_set: yes
    state: present
    reload: yes
- sysctl:
    name: net.core.wmem_max
    value: "16777216"
    sysctl_set: yes
    state: present
    reload: yes
- sysctl:
    name: net.core.rmem_default
    value: "65536"
    sysctl_set: yes
    state: present
    reload: yes
- sysctl:
    name: net.core.wmem_default
    value: "65536"
    sysctl_set: yes
    state: present
    reload: yes
- sysctl:
    name: net.core.optmem_max
    value: "65536"
    sysctl_set: yes
    state: present
    reload: yes

- name: Make room for more TIME_WAIT sockets due to more clients
  sysctl:
    name: net.ipv4.tcp_max_syn_backlog
    value: "1000"
    sysctl_set: yes
    state: absent
    reload: yes
- sysctl:
    name: net.ipv4.tcp_max_tw_buckets
    value: "2000000"
    sysctl_set: yes
    state: absent
    reload: yes

- name: Add net.ipv4.tcp_tw_reuse
  sysctl:
    name: net.ipv4.tcp_tw_reuse
    value: "1"
    sysctl_set: yes
    state: absent
    reload: yes

- name: Decreate fin timeout
  sysctl:
    name: net.ipv4.tcp_fin_timeout
    value: "10"
    sysctl_set: yes
    state: absent
    reload: yes

- name: Disable TCP slow start on idle connections
  sysctl:
    name: net.ipv4.tcp_slow_start_after_idle
    value: "0"
    sysctl_set: yes
    state: absent
    reload: yes

- name: Increase udp limits
  sysctl:
    name: net.ipv4.udp_rmem_min
    value: "4096"
    sysctl_set: yes
    state: absent
    reload: yes
- sysctl:
    name: net.ipv4.udp_wmem_min
    value: "4096"
    sysctl_set: yes
    state: absent
    reload: yes

- name: Helps reduce network latency.
  sysctl:
    name: net.ipv4.tcp_fastopen
    value: "3"
    sysctl_set: yes
    state: absent
    reload: yes

- name: Number of times SYNACKs for passive TCP connection.
  sysctl:
    name: net.ipv4.tcp_synack_retries
    value: "6"
    sysctl_set: yes
    state: absent
    reload: yes

- name: Number of times tcp_syn_retries.
  sysctl:
    name: net.ipv4.tcp_syn_retries
    value: "6"
    sysctl_set: yes
    state: absent
    reload: yes

- name: Protect Against TCP Time-Wait
  sysctl:
    name: net.ipv4.tcp_rfc1337
    value: "1"
    sysctl_set: yes
    state: absent
    reload: yes

- name: Decrease the time default value for connections to keep alive
  sysctl:
    name: net.ipv4.tcp_keepalive_time
    value: "200"
    sysctl_set: yes
    state: absent
    reload: yes
- sysctl:
    name: net.ipv4.tcp_keepalive_probes
    value: "5"
    sysctl_set: yes
    state: absent
    reload: yes
- sysctl:
    name: net.ipv4.tcp_keepalive_intvl
    value: "200"
    sysctl_set: yes
    state: absent
    reload: yes

- name: Enable MTU probing
  sysctl:
    name: net.ipv4.tcp_mtu_probing
    value: "1"
    sysctl_set: yes
    state: absent
    reload: yes

- name: Make sure window scaling is enabled
  sysctl:
    name: net.ipv4.tcp_window_scaling
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: Set tcp timestamps
  sysctl:
    name: net.ipv4.tcp_timestamps
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: Adjust TCP orphan limit
  sysctl:
    name: net.ipv4.tcp_max_orphans
    value: "262144"
    sysctl_set: yes
    state: absent
    reload: yes

- name: Ensure changes happen now
  sysctl:
    name: net.ipv4.route.flush
    value: "1"
    sysctl_set: yes
    state: absent
    reload: yes


#- name: Memory deduplication
#  sysctl:
#    name: kernel.mm.ksm.run
#    value: "1"
#    sysctl_set: yes
#    state: present
#    reload: yes
#
#- name: Memory duplication 2
#  sysctl:
#    name: kernel.mm.ksm.sleep_millisecs
#    value: "1000"
#    sysctl_set: yes
#    state: present
#    reload: yes
