---
- hosts: all
  become: true
  gather_facts: true
  strategy: free
  serial: 5
  roles:
    - swap
    - programs_default
    - programs_extra
    - sysctl
    - timezone
    - profiles
    - root_scripts
    - cron
    - ssh_users
    - docker
    - digital_ocean_metrics
