version: '3.8'
x-default-opts:
  &default-opts
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
services:
  traefik:
    image: traefik
    hostname: traefik.server
    environment:
      - "TZ=${TIME_ZONE}"
      - "CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}"
      - "DO_AUTH_TOKEN=${DIGITALOCEAN_TOKEN}"
    command:
      - "--api"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.wss.address=:6001"
      - "--entryPoints.websecure.proxyProtocol.insecure"
      - "--entrypoints.web.http.redirections.entrypoint.to=:443"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - >-
        --entryPoints.websecure.proxyProtocol.trustedIPs=127.0.0.1,10.10.0.0/16,172.17.0.0/12,173.245.48.0/20,103.21.244.0/22,
        103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,141.101.107.0/24,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,
        198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0,172.64.0.0/13,131.0.72.0/22,2400:cb00::/32,2606:4700::/32,
        2803:f800::/32,2405:b500::/32,2405:8100::/32,2a06:98c0::/29,2c0f:f248::/32
      - "--entryPoints.websecure.forwardedHeaders.insecure"
      - >-
        --entryPoints.websecure.forwardedHeaders.trustedIPs=127.0.0.1,10.10.0.0/16,172.17.0.0/12,173.245.48.0/20,103.21.244.0/22,
        103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,141.101.107.0/24,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,
        198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0,172.64.0.0/13,131.0.72.0/22,2400:cb00::/32,2606:4700::/32,
        2803:f800::/32,2405:b500::/32,2405:8100::/32,2a06:98c0::/29,2c0f:f248::/32
      - "--certificatesresolvers.le.acme.email=acme@phpsouthafrica.org"
      - "--certificatesresolvers.le.acme.dnschallenge=true"
      - "--certificatesresolvers.le.acme.dnschallenge.provider=digitalocean"
#      - "--certificatesresolvers.le.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53"
      - "--certificatesresolvers.le.acme.dnschallenge.delaybeforecheck=10"
      - "--certificatesresolvers.le.acme.storage=/acme.json"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.network=traefik-net"
      - "--accesslog=true"
      - "--accessLog.fields.defaultmode=keep"
      - "--accessLog.fields.names.ClientUsername=keep"
      - "--accessLog.fields.headers.defaultmode=keep"
      - "--accessLog.fields.headers.names.User-Agent=keep"
      - "--accessLog.fields.headers.names.Authorization=keep"
      - "--accessLog.fields.headers.names.Content-Type=keep"
      - "--accessLog.fields.headers.names.CF-Connecting-IP=keep"
      - "--accessLog.fields.headers.names.Cf-Ipcountry=keep"
      - "--accessLog.fields.headers.names.X-Forwarded-For=keep"
      - "--accessLog.fields.headers.names.X-Forwarded-Proto=keep"
      - "--accessLog.fields.headers.names.Cf-Ray=keep"
      - "--accessLog.fields.headers.names.Cf-Visitor=keep"
      - "--accessLog.fields.headers.names.True-Client-IP=keep"
    deploy:
      mode: global
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
      labels:
        - "com.ouroboros.enable=true"
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-net"
        # Dashboard
        - "traefik.http.routers.traefik.rule=Host(`traefik.${PRIMARY_DOMAIN}`)"
        - "traefik.http.routers.traefik.entryPoints=websecure"
        - "traefik.http.routers.traefik.service=api@internal"
        # Dummy service for Swarm port detection. The port can be any valid integer value.
        - "traefik.http.services.traefik.loadbalancer.server.port=9999"
        - "traefik.http.routers.traefik.tls=true"
        - "traefik.http.routers.traefik.tls.certresolver=le"
        - "traefik.http.routers.traefik.tls.domains[0].main=${PRIMARY_DOMAIN}"
        - "traefik.http.routers.traefik.tls.domains[0].sans=*.${PRIMARY_DOMAIN}"

        - "traefik.http.routers.traefik.middlewares=traefik-auth, traefik-compress"
        - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_BASIC_USER}:${TRAEFIK_BASIC_PASSWORD}"
        - "traefik.http.middlewares.traefik-compress.compress=true"

#        # global redirect to https
#        - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
#        - "traefik.http.routers.http-catchall.entrypoints=web"
#        - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
#
#        # middleware redirect
#        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    networks:
      traefik-net:
        aliases:
          - traefik.server
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 6001
        published: 6001
        protocol: tcp
        mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/root/ltencrypt/acme.json:/acme.json"
networks:
  traefik-net:
    attachable: true
    external: true
    driver: overlay
